# dhcpd.conf
#
# Sample configuration file for ISC dhcpd
#

default-lease-time 600;
max-lease-time 7200;

# The ddns-updates-style parameter controls whether or not the server will
# attempt to do a DNS update when a lease is confirmed. We default to the
# behavior of the version 2 packages ('none', since DHCP v2 didn't
# have support for DDNS.)
ddns-update-style none;

# If this DHCP server is the official DHCP server for the local
# network, the authoritative directive should be uncommented.
authoritative;

subnet 0.0 netmask 255.255.255.128 {
  range 192.168.10.100 192.168.10.126;
  option routers 192.168.10.1;
  option domain-name-servers 192.168.10.1;

  # option 66
  # tftp server and dhcp server run on the same machine
  option tftp-server-address 192.168.10.4;

  # option 67
  option bootfile-name "pxelinux.0";
}