- name: labo 9
  hosts: localhost
  gather_facts: false

  tasks:
    - name: add a user to the ESXi host
      community.vmware.vmware_local_user_manager:
        validate_certs: false
        hostname: "192.168.12.15"
        username: "root"
        password: "ESXi123"
        local_user_name: "admin"
        local_user_password: "secretpass-1234"
      delegate_to: localhost
