server {
    #listen       80;
    #listen  [::]:80
    listen  443 ssl;
    server_name  localhost;

    ssl_certificate     /etc/nginx/cert/localhost.cert;
    ssl_certificate_key /etc/nginx/cert/localhost.key;
    ssl_protocols       TLSv1.3;

    location / { # proxy requests to vikunja
        proxy_pass http://vikunja:3456;
        # wordt in sommige posts meegenomen. https lijkt even goed te werken zonder onderstaande
        #proxy_set_header Host $host; # Pass the host header
        #proxy_set_header X-Real-IP $remote_addr; # Pass the real client IP address
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Pass the X-Forwarded-For header
        #proxy_set_header X-Forwarded-Proto $scheme; # Pass the original scheme (http or https)
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
