services:
  proxy:
    image: nginx:1.27
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-net
      - frontend-net
    volumes:
      - ./default-${scheme}.conf:/etc/nginx/conf.d/default.conf
      - ./cert/${host}.cert:/etc/nginx/cert/${host}.cert
      - ./cert/${host}.key:/etc/nginx/cert/${host}.key
    depends_on:
      db:
        condition: service_healthy
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${scheme}://${host}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${vikunja_db_user_pass}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${vikunja_db_user}
      VIKUNJA_DATABASE_DATABASE: ${vikunja_db}
      VIKUNJA_SERVICE_JWTSECRET: ${vikunja_jwtsecret}
      ## dit is niet nodig als de vikunja public url https gebruikt wanneer de website zelf over https bereikt wordt
      #VIKUNJA_CORS_ENABLE: true
      #VIKUNJA_CORS_ORIGINS: "*"
    ports:
      - ${vikunja_port:-3456}:3456
    networks:
      - frontend-net
      - db-net
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${vikunja_db_root_pass}
      MYSQL_USER: ${vikunja_db_user}
      MYSQL_PASSWORD: ${vikunja_db_user_pass}
      MYSQL_DATABASE: ${vikunja_db}
    networks:
      - db-net
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

networks:
  proxy-net:
    external: true
  frontend-net:
  db-net:
