- name: Vikunja reverse-proxy install
  hosts: "{{ host | default('local') }}"
  gather_facts: true
  gather_subset:
    - "!all"
    - "os_family"
  remote_user: "{{ user }}"
  become: yes
  tasks:
      # docker installeren
    - name: Install Docker
      block:
        - name: gather package facts
          ansible.builtin.package_facts:
            manager: auto
        - name: install Docker
          ansible.builtin.import_role:
            name: dockerinstall
          vars:
            docker_user: "{{ user }}"
          when: package not in ansible_facts.packages
      tags: docker

    # SSL certifikaat aanmaken
    - name: Request SSL certificate
      ansible.builtin.import_role:
        name: certify
      vars:
        start_dir: "{{ project_dir }}"
        cert_commonname: "{{ cn }}"
        cert_provider: "{{ provider | default('self-signed') }}"
      tags: cert
      when: uri_scheme == "https"

    # containers opzetten
    - name: Deploy vikunja containers
      ansible.builtin.import_role:
        name: vikunja
      vars:
        docker_user: "{{ user }}"
      tags: vikunja

  vars:
    project_dir: "/home/{{ ansible_user }}/vikunja"
    package: "docker-ce"
