- name: Vikunja reverse-proxy install
  hosts: "{{ host | default('local') }}"
  gather_facts: true
  gather_subset:
    - "!all"
    - "os_family"
  remote_user: "{{ user }}"
  become: yes
  roles:
      # docker installeren
    - role: dockerinstall
      vars:
        docker_user: "{{ user }}"
      tags: docker

    # SSL certifikaat aanmaken
    - role: certify
      vars:
        start_dir: "{{ project_dir }}"
        cert_commonname: "{{ cn }}"
        cert_provider: "{{ provider | default('self-signed') }}"
      tags: cert
      when: uri_scheme == "https"

    # containers opzetten
    - role: vikunja
      vars:
        docker_user: "{{ user }}"
      tags: vikunja

  vars:
    project_dir: "/home/{{ ansible_user }}/vikunja"
