---
# tasks file for createuser
- name: create user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ userpass }}" # sha-512 hashed value
    create_home: true
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_file: ".ssh/id_rsa"
