---
# vars file for certify
provider: "letsencrypt"
acme_directory_staging: "https://acme-staging-v02.api.letsencrypt.org/directory"
cert_basedir: "{{ start_dir }}/ssl"
acme_account_key: "{{ cert_basedir }}/private/account.key"
acme_challenge_dir: ".well-known/acme-challenge"
cert_private_key_file: "{{ cert_commonname }}.key"
cert_private_key_path: "{{ cert_basedir }}/private/{{ cert_private_key_file }}"
cert_csr: "{{ cert_basedir }}/csr/{{ cert_commonname }}.csr"
cert_file: "{{ cert_commonname }}.pem.cert"
cert_path: "{{ cert_basedir }}/certs/{{ cert_file }}"
cert_chain: "{{ cert_basedir }}/certs/{{ cert_commonname }}-intermediate.cert"
cert_fullchain: "{{ cert_basedir }}/certs/{{ cert_commonname }}-fullchain.cert"
