---
# tasks file for grantsudo
- name: add to sudoers
  ansible.builtin.user:
    name: "{{ username }}"
    append: true
    groups: "{{ grp }}"

  vars:
    - grp: wheel
      when: ansible_facts.os_family == "RedHat"
    - grp: sudo
      when: ansible_facts.os_family == "Debian"
