name: "labo 7"
services:
  cms1:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=${db_user}
      - WORDPRESS_DB_PASSWORD=${db_pass}
      - WORDPRESS_DB_NAME=${db_name}
      - WORDPRESS_TABLE_PREFIX=wp
  database:
    image: mysql
    environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=yes
       - MYSQL_DATABASE=${db_name}
       - MYSQL_USER=${db_user}
       - MYSQL_PASSWORD=${db_pass}
