---
# tasks file for dockerinstall

- name: Set up Docker repository
  block:
    - name: install certificates package
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
        state: present
    - name: install keyrings
      ansible.builtin.command:
        cmd: install -m 0755 -d /etc/apt/keyrings
    - name: download official GPG key
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - name: change permissions on GPG key
      ansible.builtin.command:
        cmd: chmod a+r /etc/apt/keyrings/docker.asc
    - name: add repository to Apt sources
      ansible.builtin.blockinfile:
        block: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        path: /etc/apt/sources.list.d/docker.list
        create: true
        state: present
    - name: update repository
      ansible.builtin.command:
        cmd: apt update
    - name: update system
      import_role:
        name: updateall
  when: ansible_facts.os_family == "Debian"

- name: set up docker repository (Red Hat based)
  ansible.builtin.command: sudo dnf config-manager --add-repo "{{ docker_official_repo }}"
  when: ansible_facts.os_family == "RedHat"

- name: install docker
  ansible.builtin.package:
    name: "{{ docker_dependencies }}"
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Grant permission to run docker command
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"

- name: reboot
  import_role:
    name: reboot
