---
# tasks file for vikunja
- name: prepare environment
  block:
  - name: create volume directories
    ansible.builtin.file:
      path: "{{ project_dir }}/{{ item }}"
      state: directory
    with_items:
      - db
      - files
  - name: copy nginx config
    ansible.builtin.template:
      src: "default-{{ uri_scheme }}.conf.jinja2"
      dest: "{{ project_dir }}/default-{{ uri_scheme }}.conf"
  - name: Provision Docker compose file
    ansible.builtin.template:
      src: templates/docker-compose-{{ uri_scheme }}.yml.jinja2
      dest: "{{ project_dir }}/docker-compose.yml"
      mode: '0644'
      owner: "{{ docker_user }}"
      group: "{{ docker_user }}"
  tags:
    - prep

- name: deploy containers
  block:
    - name: create shared network
      community.docker.docker_network:
        name: "vikunja-net"
    - name: start containers
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: present
  tags:
    - deploy
