- hosts: wintest
  gather_facts: false
  tasks:
  - name: chocolatey  # executionpolicy no op "bypass" zetten
    win_chocolatey:
      name: chocolatey
      state: present
      source: https://community.chocolatey.org/install.ps1

  - name: install 7zip
    win_chocolatey:
      name: 7zip
      version: '24.9.0'
      state: present

  - name: Install Dropbox
    win_chocolatey:
      name: dropbox
      version: '220.4.4126'
      state: present

  - name: Install Greenshot
    win_chocolatey:
      name: greenshot
      version: '1.2.10.6'
      state: present

  - name: Install Irfanview
    win_chocolatey:
      name: irfanview
      version: '4.70.0'
      state: present

  - name: Install firefox
    win_chocolatey:
      name: firefox
      version: '136.0.4'
      state: present

  - name: Install Okular
    win_chocolatey:
      name: okular
      version: '24.12.0'
      state: present

  - name: Install python
    win_chocolatey:
      name: python
      version: '3.13.2'
      state: present

  - name: Install Notepad++
    win_chocolatey:
      name: notepadplusplus.install
      version: '8.7.8'
      state: present

  - name: Install OpenSSL
    win_chocolatey:
      name: openssl.light
      version: '3.1.4'  # outdated. Newest version is 3.4.1
      state: present

  - name: Install vlc
    win_chocolatey:
      name: vlc
      version: '3.0.21'
      state: present

  - name: Install Java JRE
    win_chocolatey:
      name: jre8
      version: '8.0.441'
      state: present

  - name: Install eid-belgium-middleware
    win_chocolatey:
      name: eid-belgium
      version: '5.0.17.5498'  # verouderde versie. Werkt niet meer voor aanmelden met e-ID. Nieuwste versie vereist
      state: present

  - name: Install eid-belgium-viewer
    win_chocolatey:
      name: eid-belgium-viewer
      version: '5.1.2.5886'  # verouderde versie
      state: present

  - name: Install Bruno API tool
    win_chocolatey:
      name: bruno
      version: '1.39.1'
      state: present

  - name: Install Node.js  # requires restart to be available from system PATH
    win_chocolatey:
      name: nodejs
      version: '23.10.0'
      state: present

  - name: Install OBS Studio  # verification testing exemption
    win_chocolatey:
      name: obs-studio
      version: '31.0.3'
      state: present

  # - name: Install
  #   win_chocolatey:
  #     name: 
  #     version: ''
  #     state: present
