- hosts: wintest
  gather_facts: false
  tasks:
  - name: chocolatey  # executionpolicy no op "bypass" zetten
    win_chocolatey:
      name: chocolatey
      state: present
      source: https://community.chocolatey.org/install.ps1

  - name: install 7zip
    win_chocolatey:
      name: 7zip
      version: '24.9.0'
      state: present

  - name: Install Dropbox
    win_chocolatey:
      name: dropbox
      version: '220.4.4126'
      state: present
