- name: Labo 5 Ansible & Windows
  hosts: wintest
  gather_facts: False
  roles:
    # - { role: rwin_hostname, host_name: "{{ hostname }}" }
    - role: rwin_update
  
  # tasks:
  # - name: add hosts entry for ansible-controller
  #   # ansible.windows.win_hosts:  # ERROR! couldn't resolve module/action 'ansible.windows.win_hosts' 
  #   community.windows.win_hosts:
  #     action: add
  #     state: present
  #     canonical_name: ansible-controller
  #     ip_address: "{{ ansible_controller }}"

  # - name: disable windows firewall
  #   community.windows.win_firewall:
  #     profiles:
  #       - "Domain"
  #       - "Private"
  #       - "Public"
  #     state: "disabled"

  # - name: enable windows firewall
  #   community.windows.win_firewall:
  #     profiles:
  #       - "Domain"
  #       - "Private"
  #       - "Public"
  #     state: "enabled"

  # - name: remove service - print spooler
  #   ansible.windows.win_service:
  #     name: spooler
  #     state: absent

  # - name: remove service - Printer Extensions and Notifications
  #   ansible.windows.win_service:
  #     name: PrintNotify
  #     state: absent

  # - name: remove service - Theme
  #   ansible.windows.win_service:
  #     name: Theme
  #     state: absent

  # - name: Local Security Policy - set minimum password length
  #   community.windows.win_security_policy:
  #     section: "System Access"
  #     key: "MinimumPasswordLength"
  #     value: 12

  # - name: remove Windows Feature - Internet Explorer 11
  #   ansible.windows.win_optional_feature:
  #     name: "Internet-Explorer-Optional-amd64"
  #     state: "absent"
  #   register: feat

  # - name: set screen timeout to 0
  #   ansible.windows.win_command:
  #     cmd: powercfg /change monitor-timeout-ac 0

  # - name: set standby timeout to 0
  #   ansible.windows.win_command:
  #     cmd: powercfg /change standby-timeout-ac 0

  # # - name: set timezone to Romance Standard time (GMT +1)
  # #   # ansible.windows.win_timezone:  # ERROR! couldn't resolve module/action
  # #   community.windows.win_timezone:
  # #     timezone: Romance Standard Time

  vars:
    hostname: "{{ lookup('file', 'hostname') }}"
    ansible_controller: "50.50.32.128"
