- name: Labo 5 Ansible & Windows
  hosts: wintest
  gather_facts: False
  tasks:
  # - name: reboot
  #   ansible.windows.win_reboot:

  - name: update Windows
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
