- name: Infrastructure As Code Labo 2
  hosts: managed-nodes
  tasks:

  - name: SELinux als permissive instellen
    ansible.builtin.command: setenforce 0
    become: yes

  - name: hostname aanpassen
    ansible.builtin.command: hostname bahamut
    become: yes

  - name: bestand aanmaken
    ansible.builtin.command: touch /test.txt
    become: yes

  - name: gebruiker jacko aanmaken
    ansible.builtin.user:
      name: jacko
      comment: voor Jan
    become: yes

  - name: SSH authorized key voor jacko instellen
    ansible.posix.authorized_key:
      user: jacko
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDimr3b/EBcBs4ienxG4sRRxjmvA1j1s2Ovi+KIf7VoCZYPMOIAA2Pa7MQQRlh6eTXPkx6tWRpIlJZDUdcc8GqZ5xTEmw+AKzys253CWiRny7nnBbIfrNhW7wye8f3dB988AZ6lwcRMXA5QxjaQC/ToEdlZ0JpA+wLlZXRhc+NA1phnnSVNAtBptlL4Bet0rFquvKNJrZKRVmbVNJ4IR0zDI8NJMnVGdKC17JswnhDVGb6g5k05wXFHGbKPVN6MSatsnBO2md2FHx0QyuHcfbFegSWB/JCQ0fYabIjFCkkJ1lqQMHHPa7OvPGYii5u3STVgQL19G8YDI6ORLhILu+en jacko@MacBook-Pro.local"
    become: yes

  - name: Docker - install dnf plugin
    ansible.builtin.dnf:
      name: dnf-plugins-core
      state: present
    become: yes
