- name: Infrastructure As Code Labo 2
  hosts: managed-nodes
  tasks:

  - name: SELinux als permissive instellen
    ansible.builtin.command: setenforce 0
    become: yes

  - name: hostname aanpassen
    ansible.builtin.command: hostname bahamut
    become: yes

  - name: bestand aanmaken
    ansible.builtin.command: touch /test.txt
    become: yes

  - name: gebruiker jacko aanmaken
    ansible.builtin.user:
      name: jacko
      comment: voor Jan
    become: yes
